/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho01_restaurante;

import java.util.Random;


/**
 *
 * @author Alex e Luan
 */
public class CadastroProduto extends javax.swing.JFrame {
    
    /**
     * Creates new form Cliente
     */
    public CadastroProduto() {
        initComponents();
        geraAleatorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSexo = new javax.swing.ButtonGroup();
        btnGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lCadastroProduto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lCodProduto = new javax.swing.JLabel();
        tCodProduto = new javax.swing.JTextField();
        lNome = new javax.swing.JLabel();
        tNomeProduto = new javax.swing.JTextField();
        lPrecoCompra = new javax.swing.JLabel();
        tPrecoCompra = new javax.swing.JTextField();
        lPrecoVenda = new javax.swing.JLabel();
        tPrecoVenda = new javax.swing.JTextField();
        lUnidadeMedida = new javax.swing.JLabel();
        tUniMedida = new javax.swing.JTextField();
        lTipo = new javax.swing.JLabel();
        rBtnLiquido = new javax.swing.JRadioButton();
        rBtnSolido = new javax.swing.JRadioButton();
        bSalvar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lAlcoolico = new javax.swing.JLabel();
        rBtnSim = new javax.swing.JRadioButton();
        rBtnNao = new javax.swing.JRadioButton();
        lQuantidade = new javax.swing.JLabel();
        tQuatidade = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lPeso = new javax.swing.JLabel();
        tPeso = new javax.swing.JTextField();
        lIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Produto");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(219, 82, 82));

        lCadastroProduto.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lCadastroProduto.setText("Cadastro de Produto");

        jPanel2.setBackground(new java.awt.Color(219, 82, 82));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados de Identificação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 12), new java.awt.Color(39, 39, 39))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(39, 39, 39));

        lCodProduto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lCodProduto.setForeground(new java.awt.Color(39, 39, 39));
        lCodProduto.setText("Codigo Produto:");

        tCodProduto.setEditable(false);
        tCodProduto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCodProdutoActionPerformed(evt);
            }
        });

        lNome.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lNome.setForeground(new java.awt.Color(39, 39, 39));
        lNome.setText("Nome:");

        tNomeProduto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        lPrecoCompra.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lPrecoCompra.setForeground(new java.awt.Color(39, 39, 39));
        lPrecoCompra.setText("Preço de Compra");

        tPrecoCompra.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tPrecoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrecoCompraActionPerformed(evt);
            }
        });

        lPrecoVenda.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lPrecoVenda.setForeground(new java.awt.Color(39, 39, 39));
        lPrecoVenda.setText("Preço de Venda");

        tPrecoVenda.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrecoVendaActionPerformed(evt);
            }
        });

        lUnidadeMedida.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lUnidadeMedida.setForeground(new java.awt.Color(39, 39, 39));
        lUnidadeMedida.setText("Unidade de Medida");

        tUniMedida.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        lTipo.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lTipo.setForeground(new java.awt.Color(39, 39, 39));
        lTipo.setText("Tipo:");

        rBtnLiquido.setBackground(new java.awt.Color(219, 82, 82));
        btnGroupTipo.add(rBtnLiquido);
        rBtnLiquido.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rBtnLiquido.setSelected(true);
        rBtnLiquido.setText("Líquido");

        rBtnSolido.setBackground(new java.awt.Color(219, 82, 82));
        btnGroupTipo.add(rBtnSolido);
        rBtnSolido.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rBtnSolido.setText("Sólido");

        bSalvar.setBackground(new java.awt.Color(219, 82, 82));
        bSalvar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bCancelar.setBackground(new java.awt.Color(219, 82, 82));
        bCancelar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(219, 82, 82));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Líquido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 12), new java.awt.Color(39, 39, 39))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(39, 39, 39));

        lAlcoolico.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lAlcoolico.setForeground(new java.awt.Color(39, 39, 39));
        lAlcoolico.setText("Alcoólico");

        rBtnSim.setBackground(new java.awt.Color(219, 82, 82));
        btnGroupSexo.add(rBtnSim);
        rBtnSim.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rBtnSim.setText("Sim");

        rBtnNao.setBackground(new java.awt.Color(219, 82, 82));
        btnGroupSexo.add(rBtnNao);
        rBtnNao.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rBtnNao.setSelected(true);
        rBtnNao.setText("Não");

        lQuantidade.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lQuantidade.setForeground(new java.awt.Color(39, 39, 39));
        lQuantidade.setText("Quantidade");

        tQuatidade.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tQuatidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tQuatidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBtnNao)
                    .addComponent(lAlcoolico)
                    .addComponent(rBtnSim)
                    .addComponent(tQuatidade, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lQuantidade))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lAlcoolico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBtnNao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBtnSim)
                .addGap(18, 18, 18)
                .addComponent(lQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tQuatidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(219, 82, 82));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sólido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 12), new java.awt.Color(39, 39, 39))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(39, 39, 39));

        lPeso.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lPeso.setForeground(new java.awt.Color(39, 39, 39));
        lPeso.setText("Peso");

        tPeso.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lPeso)
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addComponent(tPeso))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tCodProduto)
                                    .addComponent(lCodProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNome)
                                    .addComponent(tNomeProduto)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lPrecoCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tPrecoCompra))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lTipo)
                                        .addGap(18, 18, 18)
                                        .addComponent(rBtnLiquido)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rBtnSolido)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lPrecoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lUnidadeMedida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tUniMedida))))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lCodProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lNome))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lPrecoVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tUniMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lPrecoCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lUnidadeMedida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTipo)
                    .addComponent(rBtnLiquido)
                    .addComponent(rBtnSolido))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho01_restaurante/imagens/addProduto.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lCadastroProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCadastroProduto)
                    .addComponent(lIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCodProdutoActionPerformed

    }//GEN-LAST:event_tCodProdutoActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSalvarActionPerformed

    private void tPrecoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrecoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPrecoCompraActionPerformed

    private void tQuatidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tQuatidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tQuatidadeActionPerformed

    private void tPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPrecoVendaActionPerformed

    private void tPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPesoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bSalvar;
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.ButtonGroup btnGroupTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lAlcoolico;
    private javax.swing.JLabel lCadastroProduto;
    private javax.swing.JLabel lCodProduto;
    private javax.swing.JLabel lIcon;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPeso;
    private javax.swing.JLabel lPrecoCompra;
    private javax.swing.JLabel lPrecoVenda;
    private javax.swing.JLabel lQuantidade;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lUnidadeMedida;
    private javax.swing.JRadioButton rBtnLiquido;
    private javax.swing.JRadioButton rBtnNao;
    private javax.swing.JRadioButton rBtnSim;
    private javax.swing.JRadioButton rBtnSolido;
    private javax.swing.JTextField tCodProduto;
    private javax.swing.JTextField tNomeProduto;
    private javax.swing.JTextField tPeso;
    private javax.swing.JTextField tPrecoCompra;
    private javax.swing.JTextField tPrecoVenda;
    private javax.swing.JTextField tQuatidade;
    private javax.swing.JTextField tUniMedida;
    // End of variables declaration//GEN-END:variables

    public void geraAleatorio(){
        Random gerador = new Random();
        String cod = new String();
        cod = String.valueOf(gerador.nextInt(26));
        tCodProduto.setText(cod);
    }
}


/*
    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
/*        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

*/