/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho01_restaurante;

/**
 *
 * @author ALEX e LUAN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenuLateral = new javax.swing.JPanel();
        jpCardapio = new javax.swing.JPanel();
        jlCardapio = new javax.swing.JLabel();
        iconCardapio = new javax.swing.JLabel();
        jpAddPedido = new javax.swing.JPanel();
        jlAdicionarPedido = new javax.swing.JLabel();
        iconAddPedido = new javax.swing.JLabel();
        jpAddProduto = new javax.swing.JPanel();
        jlAdicionarProduto = new javax.swing.JLabel();
        iconAddProduto = new javax.swing.JLabel();
        jpClientes = new javax.swing.JPanel();
        jlClientes = new javax.swing.JLabel();
        iconCliente = new javax.swing.JLabel();
        jpFuncionarios = new javax.swing.JPanel();
        jlFuncionarios = new javax.swing.JLabel();
        iconFuncionario = new javax.swing.JLabel();
        jlMenu = new javax.swing.JLabel();
        jpSobre = new javax.swing.JPanel();
        jlSobre = new javax.swing.JLabel();
        iconSobre = new javax.swing.JLabel();
        jpPedidos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        jlPedidos = new javax.swing.JLabel();
        btnFecharPedido = new javax.swing.JButton();
        btnAlterarPedido = new javax.swing.JButton();
        jlRestaurante = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenuLateral.setBackground(new java.awt.Color(219, 82, 82));
        jpMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpCardapio.setBackground(new java.awt.Color(254, 131, 131));

        jlCardapio.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jlCardapio.setForeground(new java.awt.Color(39, 39, 39));
        jlCardapio.setText("Cardápio");

        iconCardapio.setForeground(new java.awt.Color(39, 39, 39));
        iconCardapio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCardapio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho01_restaurante/imagens/cardapio.png"))); // NOI18N

        javax.swing.GroupLayout jpCardapioLayout = new javax.swing.GroupLayout(jpCardapio);
        jpCardapio.setLayout(jpCardapioLayout);
        jpCardapioLayout.setHorizontalGroup(
            jpCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCardapioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(iconCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlCardapio)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jpCardapioLayout.setVerticalGroup(
            jpCardapioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCardapioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCardapio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(iconCardapio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpMenuLateral.add(jpCardapio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 40));

        jpAddPedido.setBackground(new java.awt.Color(254, 131, 131));
        jpAddPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAddPedidoMouseClicked(evt);
            }
        });

        jlAdicionarPedido.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jlAdicionarPedido.setForeground(new java.awt.Color(39, 39, 39));
        jlAdicionarPedido.setText("Adicionar um pedido");

        iconAddPedido.setForeground(new java.awt.Color(39, 39, 39));
        iconAddPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAddPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho01_restaurante/imagens/addPedido.png"))); // NOI18N

        javax.swing.GroupLayout jpAddPedidoLayout = new javax.swing.GroupLayout(jpAddPedido);
        jpAddPedido.setLayout(jpAddPedidoLayout);
        jpAddPedidoLayout.setHorizontalGroup(
            jpAddPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddPedidoLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(iconAddPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlAdicionarPedido)
                .addGap(32, 32, 32))
        );
        jpAddPedidoLayout.setVerticalGroup(
            jpAddPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAdicionarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(iconAddPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpMenuLateral.add(jpAddPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 260, 40));

        jpAddProduto.setBackground(new java.awt.Color(254, 131, 131));

        jlAdicionarProduto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jlAdicionarProduto.setForeground(new java.awt.Color(39, 39, 39));
        jlAdicionarProduto.setText("Adicionar um produto");

        iconAddProduto.setForeground(new java.awt.Color(39, 39, 39));
        iconAddProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho01_restaurante/imagens/addProduto.png"))); // NOI18N

        javax.swing.GroupLayout jpAddProdutoLayout = new javax.swing.GroupLayout(jpAddProduto);
        jpAddProduto.setLayout(jpAddProdutoLayout);
        jpAddProdutoLayout.setHorizontalGroup(
            jpAddProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddProdutoLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(iconAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlAdicionarProduto)
                .addGap(25, 25, 25))
        );
        jpAddProdutoLayout.setVerticalGroup(
            jpAddProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAdicionarProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(iconAddProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpMenuLateral.add(jpAddProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 260, 40));

        jpClientes.setBackground(new java.awt.Color(254, 131, 131));

        jlClientes.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jlClientes.setForeground(new java.awt.Color(39, 39, 39));
        jlClientes.setText("Clientes");

        iconCliente.setForeground(new java.awt.Color(39, 39, 39));
        iconCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho01_restaurante/imagens/clientes.png"))); // NOI18N

        javax.swing.GroupLayout jpClientesLayout = new javax.swing.GroupLayout(jpClientes);
        jpClientes.setLayout(jpClientesLayout);
        jpClientesLayout.setHorizontalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(iconCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlClientes)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jpClientesLayout.setVerticalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(iconCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpMenuLateral.add(jpClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 260, 40));

        jpFuncionarios.setBackground(new java.awt.Color(254, 131, 131));

        jlFuncionarios.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jlFuncionarios.setForeground(new java.awt.Color(39, 39, 39));
        jlFuncionarios.setText("Funcionários");

        iconFuncionario.setForeground(new java.awt.Color(39, 39, 39));
        iconFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho01_restaurante/imagens/funcionarios.png"))); // NOI18N

        javax.swing.GroupLayout jpFuncionariosLayout = new javax.swing.GroupLayout(jpFuncionarios);
        jpFuncionarios.setLayout(jpFuncionariosLayout);
        jpFuncionariosLayout.setHorizontalGroup(
            jpFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFuncionariosLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(iconFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlFuncionarios)
                .addGap(83, 83, 83))
        );
        jpFuncionariosLayout.setVerticalGroup(
            jpFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlFuncionarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(iconFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpMenuLateral.add(jpFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 260, 40));

        jlMenu.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jlMenu.setText("Menu");
        jpMenuLateral.add(jlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 50, -1, -1));

        jpSobre.setBackground(new java.awt.Color(254, 131, 131));

        jlSobre.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jlSobre.setForeground(new java.awt.Color(39, 39, 39));
        jlSobre.setText("Sobre");

        iconSobre.setForeground(new java.awt.Color(39, 39, 39));
        iconSobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho01_restaurante/imagens/sobre.png"))); // NOI18N

        javax.swing.GroupLayout jpSobreLayout = new javax.swing.GroupLayout(jpSobre);
        jpSobre.setLayout(jpSobreLayout);
        jpSobreLayout.setHorizontalGroup(
            jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSobreLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(iconSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlSobre)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jpSobreLayout.setVerticalGroup(
            jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSobre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(iconSobre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpMenuLateral.add(jpSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 260, 40));

        getContentPane().add(jpMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 630));

        jpPedidos.setBackground(new java.awt.Color(194, 44, 44));
        jpPedidos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        tablePedidos.setAutoCreateRowSorter(true);
        tablePedidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablePedidos.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tablePedidos.setForeground(new java.awt.Color(39, 39, 39));
        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(212), "Jorge", null,  new Double(79.88)},
                { new Integer(2),  new Integer(473), "Alex", null,  new Double(54.7)},
                { new Integer(3),  new Integer(23), "Maria", null,  new Double(99.65)},
                { new Integer(4),  new Integer(540), "Luan", null,  new Double(64.75)}
            },
            new String [] {
                "Código do pedido", "N° do cliente", "Nome do cliente", "Produtos", "Preço Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePedidos.setCellSelectionEnabled(true);
        tablePedidos.setName(""); // NOI18N
        tablePedidos.setSelectionBackground(new java.awt.Color(254, 131, 131));
        tablePedidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablePedidos);

        jpPedidos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 810, 310));

        jlPedidos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jlPedidos.setForeground(new java.awt.Color(39, 39, 39));
        jlPedidos.setText("Pedidos");
        jpPedidos.add(jlPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnFecharPedido.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnFecharPedido.setForeground(new java.awt.Color(39, 39, 39));
        btnFecharPedido.setText("Fechar Pedido");
        btnFecharPedido.setEnabled(false);
        jpPedidos.add(btnFecharPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        btnAlterarPedido.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnAlterarPedido.setForeground(new java.awt.Color(39, 39, 39));
        btnAlterarPedido.setText("Alterar Pedido");
        btnAlterarPedido.setEnabled(false);
        jpPedidos.add(btnAlterarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        getContentPane().add(jpPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 850, 410));

        jlRestaurante.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jlRestaurante.setForeground(new java.awt.Color(39, 39, 39));
        jlRestaurante.setText("Restaurante");
        getContentPane().add(jlRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        btnLogout.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, -1, -1));

        btnFechar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 580, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpAddPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAddPedidoMouseClicked
        System.out.println("Cliquei em Adicionar Pedido");
    }//GEN-LAST:event_jpAddPedidoMouseClicked

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarPedido;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFecharPedido;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel iconAddPedido;
    private javax.swing.JLabel iconAddProduto;
    private javax.swing.JLabel iconCardapio;
    private javax.swing.JLabel iconCliente;
    private javax.swing.JLabel iconFuncionario;
    private javax.swing.JLabel iconSobre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlAdicionarPedido;
    private javax.swing.JLabel jlAdicionarProduto;
    private javax.swing.JLabel jlCardapio;
    private javax.swing.JLabel jlClientes;
    private javax.swing.JLabel jlFuncionarios;
    private javax.swing.JLabel jlMenu;
    private javax.swing.JLabel jlPedidos;
    private javax.swing.JLabel jlRestaurante;
    private javax.swing.JLabel jlSobre;
    private javax.swing.JPanel jpAddPedido;
    private javax.swing.JPanel jpAddProduto;
    private javax.swing.JPanel jpCardapio;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpFuncionarios;
    private javax.swing.JPanel jpMenuLateral;
    private javax.swing.JPanel jpPedidos;
    private javax.swing.JPanel jpSobre;
    private javax.swing.JTable tablePedidos;
    // End of variables declaration//GEN-END:variables
}
