/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho01_restaurante;

/**
 *
 * @author ALEX e LUAN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlRestaurante = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlLogin = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        jpSenha = new javax.swing.JPasswordField();
        iconAddPedido2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Restaurante");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 82, 82));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlRestaurante.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jlRestaurante.setForeground(new java.awt.Color(39, 39, 39));
        jlRestaurante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRestaurante.setText("Restaurante");
        jlRestaurante.setMaximumSize(new java.awt.Dimension(112, 25));
        jlRestaurante.setMinimumSize(new java.awt.Dimension(112, 25));
        jlRestaurante.setPreferredSize(new java.awt.Dimension(112, 25));
        jPanel1.add(jlRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 130, 110, -1));

        jlSenha.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jlSenha.setForeground(new java.awt.Color(39, 39, 39));
        jlSenha.setText("Senha:");
        jPanel1.add(jlSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jlUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(39, 39, 39));
        jlUsuario.setText("Usuário:");
        jPanel1.add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jlLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jlLogin.setForeground(new java.awt.Color(39, 39, 39));
        jlLogin.setText("Login");
        jPanel1.add(jlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 60, -1, -1));

        jtUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jtUsuario.setForeground(new java.awt.Color(39, 39, 39));
        jPanel1.add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 420, 40));

        btnFechar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        jPanel1.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        btnEntrar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, -1, -1));

        jpSenha.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jpSenha.setForeground(new java.awt.Color(39, 39, 39));
        jPanel1.add(jpSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 292, 420, 40));

        iconAddPedido2.setForeground(new java.awt.Color(39, 39, 39));
        iconAddPedido2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAddPedido2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho01_restaurante/imagens/login.png"))); // NOI18N
        jPanel1.add(iconAddPedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 90, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel iconAddPedido2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlRestaurante;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
